name: iagno
adopt-info: iagno
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core20

slots:
  # for GtkApplication registration
  iagno:
    interface: dbus
    bus: session
    name: org.gnome.Reversi

apps:
  iagno:
    extensions: [ gnome-3-38 ]
    common-id: org.gnome.Reversi.desktop
    command: usr/bin/iagno
    desktop: usr/share/applications/org.gnome.Reversi.desktop
    plugs:
      - audio-playback

parts:
  iagno:
    source: https://gitlab.gnome.org/GNOME/iagno.git
    source-type: git
    source-branch: gnome-3-36
    parse-info: [usr/share/metainfo/org.gnome.Reversi.appdata.xml]
    plugin: meson
    meson-parameters: [ --prefix=/snap/iagno/current/usr ]
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10)
    override-build: |
      sed -i.bak -e 's|=org.gnome.Reversi$|=${SNAP}/meta/gui/iagno.png|g' $SNAPCRAFT_PART_SRC/data/org.gnome.Reversi.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/256x256/org.gnome.Reversi.png $SNAPCRAFT_PART_INSTALL/meta/gui/iagno.png
      cp $SNAPCRAFT_PART_BUILD/data/org.gnome.Reversi.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    organize:
      snap/iagno/current/usr: usr
